Repository pantamisa/Veterinaria-el-zancudo, pull requests merged in 2025-08, with the labels that each got.

#1 Feat menu implemet
  Model/Menu.py
Labels: enhancement

#7 Dev a Qa
  Model/Animal.py
  Model/Manejo _animales.py
  Model/Menu.py
Labels: enhancement

#15 Clase Animal modificado y nuevo archivo factura.py
  Model/Animal.py
  Model/factura.py
Labels: documentation, enhancement

#20 Feat clase animal factura
  Model/Animal.py
  Model/factura.py
  README.md
Labels: documentation

#23 Feat implementacion menu
  Model/Animal.py
  Model/Manejo_animales.py
  Model/Menu.py
  Model/Servicios.py
  Model/__pycache__/Animal.cpython-313.pyc
  Model/__pycache__/Manejo_animales.cpython-313.pyc
  Model/__pycache__/Servicios.cpython-313.pyc
  Model/__pycache__/factura.cpython-313.pyc
  Model/factura.py
Labels: duplicate

#24 Update README.md
  README.md
Labels: documentation

#26 Update README.md
  README.md
Labels: documentation

#25 Update README.md
  README.md
Labels: documentation
