Repository pantamisa/Veterinaria-el-zancudo, pull requests merged in 2025-09, with the labels that each got.

#43 Feat coneccion neon
  .env
  .gitignore
  Database/__pycache__/__init__.cpython-313.pyc
  Database/__pycache__/config.cpython-313.pyc
  Entities/Citas.py
  Entities/Raza_animal.py
  Entities/Servicios.py
  Entities/Tipo_animal.py
  Entities/__pycache__/Citas.cpython-313.pyc
  Entities/__pycache__/Raza_animal.cpython-313.pyc
  Entities/__pycache__/Servicios.cpython-313.pyc
  Entities/__pycache__/Tipo_animal.cpython-313.pyc
  Entities/__pycache__/__init__.cpython-313.pyc
  Entities/__pycache__/animal.cpython-313.pyc
  Entities/__pycache__/genero.cpython-313.pyc
  Entities/__pycache__/usuario.cpython-313.pyc
  Entities/animal.py
  Entities/genero.py
  Entities/usuario.py
  Model/Menu.py
  Model/__pycache__/Animal.cpython-313.pyc
  Model/__pycache__/Menu.cpython-313.pyc
  Model/__pycache__/factura.cpython-313.pyc
  Testconection.py
  alembic.ini
  migrations/__pycache__/env.cpython-313.pyc
  migrations/env.py
  requirements.txt
Labels: enhancement

#45 ORM folder y database .txt eliminado
  Database/database(pueda q no vaya).txt
Labels: bug, documentation

#46 Feat coneccion neon
  Database/__pycache__/__init__.cpython-313.pyc
  Database/__pycache__/config.cpython-313.pyc
  Entities/__pycache__/Citas.cpython-313.pyc
  Entities/__pycache__/Raza_animal.cpython-313.pyc
  Entities/__pycache__/Servicios.cpython-313.pyc
  Entities/__pycache__/Tipo_animal.cpython-313.pyc
  Entities/__pycache__/__init__.cpython-313.pyc
  Entities/__pycache__/animal.cpython-313.pyc
  Entities/__pycache__/genero.cpython-313.pyc
  Entities/__pycache__/usuario.cpython-313.pyc
  Entities/usuario.py
  Model/Manejo_animales.py
  Model/__pycache__/Menu.cpython-313.pyc
  Poblar.py
Labels: enhancement

#51 Feat actualizacion de crud
  Crud/Servicio_crud.py
  Crud/Usuario_crud.py
  Crud/__init__.py
  Crud/utils_password.py
  Entities/Citas.py
  Entities/Factura.py
  Entities/Servicios.py
  Entities/__pycache__/Citas.cpython-313.pyc
  Entities/__pycache__/Servicios.cpython-313.pyc
  Entities/__pycache__/animal.cpython-313.pyc
  Entities/__pycache__/usuario.cpython-313.pyc
  Entities/animal.py
  Entities/usuario.py
  Poblar.py
Labels: bug, documentation, duplicate, enhancement

#52 Feat creacion de datos de prueba
  Crud/Animal_crud.py
  Crud/Citas_crud.py
  Crud/Razaanimal_crud.py
  Crud/Servicios_crud.py
  Crud/Tipoanimal_crud.py
  Entities/__pycache__/Citas.cpython-313.pyc
  Entities/__pycache__/Raza_animal.cpython-313.pyc
  Entities/__pycache__/Servicios.cpython-313.pyc
  Entities/__pycache__/Tipo_animal.cpython-313.pyc
  Entities/__pycache__/__init__.cpython-313.pyc
  Entities/__pycache__/animal.cpython-313.pyc
  Entities/__pycache__/genero.cpython-313.pyc
  Entities/__pycache__/usuario.cpython-313.pyc
  Entities/animal.py
  Poblar.py
Labels: bug, enhancement
